export const SET_FAVORITE = 'SET_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const GET_VIDEO_SOURCE = 'GET_VIDEO_SOURCE';